'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Report

    '''<summary>
    '''form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''scriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''tbSAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSAS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCONTRATO_CTRLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCONTRATO_CTRLID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCONTRATO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCONTRATO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLOGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLOGO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLAT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLON As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''topLeftImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLeftImg As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lTitelo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitelo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitelo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitelo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitelo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitelo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitelo7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''topRightImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topRightImg As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lCTRLTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCTRLTYPE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCTRLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCTRLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCOORD_GEO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCOORD_GEO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lLAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lLAT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lLON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lLON As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lALT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lALT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCOORD_CARTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCOORD_CARTO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lX As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lZ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lZ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDESCRIPCION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDESCRIPCION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDesc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updatePnlDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePnlDesc As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ASPsaveDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPsaveDesc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbCROQUIS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCROQUIS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlCroquis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCroquis As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updatePnlCroquis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePnlCroquis As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ASPsaveCroquis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPsaveCroquis As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''topLeftImg_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLeftImg_P2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lTitelo1_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitelo1_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitulo2_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitulo2_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitulo3_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitulo3_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitulo4_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitulo4_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitulo5_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitulo5_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitulo6_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitulo6_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lTitulo7_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitulo7_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''topRightImg_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topRightImg_P2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lCTRLTYPE_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCTRLTYPE_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCTRLID_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCTRLID_P2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sqlCONTROL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlCONTROL As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlCONTRATO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlCONTRATO As Global.System.Web.UI.WebControls.SqlDataSource
End Class
