'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebMap

    '''<summary>
    '''frmPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPanel As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''scriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''tbSAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSAS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlCTRL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCTRL As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updatePnlCTRL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePnlCTRL As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ASPsaveNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPsaveNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ASPsaveChg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPsaveChg As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ASPdelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPdelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbCONTRATO_CTRLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCONTRATO_CTRLID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbEX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEX As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbX As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCONTRATO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCONTRATO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCTRLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCTRLID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddCTRLTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddCTRLTYPE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbDESCRIPCION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDESCRIPCION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLAT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLON As Global.System.Web.UI.WebControls.TextBox
End Class
